### PR TITLE
Fixed a bug which caused allow_redirects to be listed twice in python requests

### LINKED ISSUE #73: allow_redirects being added twice in Python requests
Generated snippet
```response = requests.request("GET", url, headers=headers, data = payload, allow_redirects=False, allow_redirects=false)```

### PR DESCRIPTION
**Pull request by shreys7**
This PR fixes #73

### CODE REVIEW

**Comment by abhijitkane** [comment]
> This PR foxes #73
Really?

File: codegens/python-requests/lib/python-requests.js [hunk 1]
```diff
@@ -110,7 +110,6 @@ self = module.exports = {
       ', data = payload, files = files' : ', data = payload';
     snippet += !options.followRedirect ? ', allow_redirects=False' : '';
```
Comment (VShingala) [inline codegens/python-requests/lib/python-requests.js]: Leave space behind and after `=` in `allow_redirects=False` in generated python code. as we are doing the same in other places. i.e `data = payload` and `files = files`.

File: codegens/python-requests/test/unit/converter.test.js [hunk 2]
```diff
@@ -153,4 +153,31 @@ describe('Python- Requests converter', function () {
...
+  it('should not have allow_redirects=False twice in generated snippet when' +
+  ' followRedirect option is set as false', function () {
+    var request = new sdk.Request(mainCollection.item[0].request),
+      options = { followRedirect: false };
+    convert(request, options, function (err, snippet) {
+      if (err) {
+        expect.fail(null, null, err);
+      }
+      expect(snippet).to.be.a('string');
+      expect(snippet).to.not.include('allow_redirects=False, allow_redirects=false');
```
Comment (VShingala) [inline codegens/python-requests/test/unit/converter.test.js]: If `options.requestTimeout !== 0` is true than this will be not valid as generated snippet will have `allow_redirects=False, timeout=${options.requestTimeout}, allow_redirects=false`.
