### PR TITLE
Move test file creation step from ci-requirements script to test script for form data testing

### LINKED ISSUE #172: Fixture is not able to find the file path in case of formdataFileCollection
**Describe the bug**
The **`formdataFileCollection`** fixture is not able to locate the exact path where `Newman` is trying to upload the files when testing the `codegens` locally.

**To Reproduce**
Run **`npm test nodejs-request`**

**Expected code snippet and corresponding request**
This can be solved by making the test.sh script to first create the required files with sample data and then running `addPathToFormdataFile.js` file.

**Screenshots**
image

**Additional context**
I would like to work on this issue.

### PR DESCRIPTION
**Pull request by shreys7**
Previously, the files required for testing form data file uploads were created using `ci-requirements.sh` step. This file is not run locally and hence would cause form-data tests to fail locally. This step has been removed from `ci-requirements.sh` file and moved to `test.sh` file.
This fixes #172

### CODE REVIEW

**Comment by sastava007** [comment]
@shreys7 I have already mentioned in the PR, that I'm working on this issue!

File: npm/test.sh [hunk 1]
```diff
@@ -12,6 +12,13 @@ else
     exit 1;
 fi
 popd &>/dev/null
+
+echo "Creating test files and adding paths to collection for testing form data file uploads"
+echo "Sample file 1" >> dummyFile1.txt;
```
Comment (sastava007) [inline npm/test.sh]: @shreys7 
Can we not have a check that creates the test file only when it doesn't exist and otherwise skip it, this would save the unnecessary time.
```
if [ ! -e test1.txt ];
then 
    echo "Sample file 1" >> dummyFile1.txt;
```
_Just suggesting_

Comment (shreys7) [reply npm/test.sh]: Added this @sastava007

**Comment by umeshp7** [comment]
@shreys7 Need rebasing with develop for branch tests to pass.
