### PR TITLE
Added the formdata fix in csharp-restsharp, and added dotnet compiler support

### LINKED ISSUE #100: Form-data POST request doesn't work as expected in csharp-restsharp
The below is the snippet generated for form data request:
```
var client = new RestClient("https://postman-echo.com/post");
client.Timeout = -1;
var request = new RestRequest(Method.POST);
request.AddParameter("a", "b");
request.AddParameter("c", "d");
IRestResponse response = client.Execute(request);
Console.WriteLine(response.Content);
```

Copy pasting this snippet and executing it actually sends the data as application/x-www-form-urlencoded instead of multipart/form-data.

### PR DESCRIPTION
**Pull request by shreys7**
This PR fixes #100

### CODE REVIEW

File: codegens/csharp-restsharp/lib/restsharp.js [hunk 1]
```diff
@@ -30,6 +30,19 @@ function makeSnippet (request, options) {
...
+  if (request.body && request.body.mode === 'formdata') {
+    let isFile = false;
+    request.body.toJSON().formdata.forEach((data) => {
+      if (!data.disabled && data.type === 'file') {
+        isFile = true;
+      }
+    });
+    // The following statement needs to be added else the multipart/form-data request where there is no file
+    // is being sent as x-www-form-urlencoded by default
+    if (!isFile) {
```
Comment (umeshp7) [inline codegens/csharp-restsharp/lib/restsharp.js]: Is this necessary to do? 
Will it be okay if we use  AlwaysMultipartFormData for all kind of formdata requests?

Comment (shreys7) [reply codegens/csharp-restsharp/lib/restsharp.js]: whenever there is a file, this parameter isn't necessary. It converts to multipart/form-data itself. This parameter only needs to be added when you have only text fields.
